### ISSUE TITLE
It's abuse

### ISSUE THREAD

**Issue by steelbrain** [Rossem/RedditStorage#1]
Reddit wasn't meant for this, It's against their TOS I am sure.

**Comment by anko** [comment]
I think it's the intention here was clearly to make a fun [hack](http://www.catb.org/jargon/html/meaning-of-hack.html), not to attack Reddit. For anyone smart enough to operate this, there are countless easier ways to freely store data online.

**Comment by evinugur** [comment]
Plus you have to remember reddit *is* open source. Someone could theoretically host their own instance of reddit and use this.

**Comment by ron-wolf** [comment]
Literally every comment here is 100% correct.

**Comment by Rossem** [comment]
^

**Comment by Dashed** [comment]
maybe a disclaimer in the README can 'clarify'

**Comment by evinugur** [comment]
Submit a PR then ;)

**Comment by willsr** [comment]
eh, I think the actual usage of this would constitute a drop in the bucket for Reddit, bandwidth/storage wise.

**Comment by evinugur** [comment]
@willsr, you're right about that, however Reddit would be more concerned with the consumption of subreddits being used for unintended purposes since someone could theoretically *claim* subreddits that have value to people who'd want to use them for their actual purpose. It's more of an ethical breach than a technical consumption of resources if used maliciously.

But................. 

This is all moot since this project is just a hack and it won't be widely used outside of the people it as you and others in this thread have pointed out.
