### ISSUE TITLE
Project turns creators and users into monsters

### ISSUE THREAD

**Issue by BrandonY** [Rossem/RedditStorage#2]
Steps to reproduce:

1. Implement RedditStorage, or make use of it at scale.
2. Examine oneself via a plane mirror.

Expected behavior

Image in mirror is of a person and not of a monster.

Actual behavior

Image in mirror is a monster, albeit a cool and clever one.

**Comment by davidcox143** [comment]
While it's kind of a shitty thing to do (especially if used at scale), it's up to Reddit to prevent this kind of stuff. 

I don't think limiting post frequency would be a good idea since there are many helpful bots, rather I think Reddit should limit the total amount of entropy in text posts. Issue closed?
